sudo: false
language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
before_install:
  - gem update --system # Need for Ruby 2.5.0. https://github.com/travis-ci/travis-ci/issues/8978
script: bundle exec rake test
